### ISSUE TITLE
Needs Hard Refresh

### ISSUE THREAD

**Issue by Aslan11** [stakes/Frameless#10]
Great job on this browser, extremely helpful for prototyping phonegap/cordova builds. I that I was unable to refresh. Selecting the URL bar and pressing go did not refresh the window, as if it new it was the same address. I'd like to suggest a small refresh icon to the right of the URL bar to do a full page reload. Thanks!

**Comment by stakes** [comment]
Hiya there @Aslan11 - did you ever get a chance to test this branch and see if it solved your issue? Let me know if so!

**Comment by stakes** [comment]
I'm going to close this out unless anyone else reports issues with this. Thanks!

**Comment by ashleyhindle** [comment]
Hi Stakes,

I'm having a cache issue currently.  I'm refreshing the page but it still has old JS and CSS.

Is it easy for me to build the `cache` branch and add it to my iPad for testing?  This isn't something I've done before :)

**Comment by andiCR** [comment]
Hey @stakes,Frameless is not refreshing my js. Please help!

**Comment by awinchestermaria** [comment]
Same problem here!

**Comment by stakes** [comment]
Thanks guys for reporting. I don't have a ton of time to work on this right now, but @ashleyhindle if you're still interested you can absolutely build and test, and if you need help or pointers in the right direction let me know!

**Comment by JeffreyBouva** [comment]
Still having this problem, how can you refresh now. Do I close the app or something ?

**Comment by stakes** [comment]
Hey @JeffreyBouva I haven't been maintaining Frameless for some time now :( if you are using it for Framer prototyping I would recommend getting into Framer's official iOS app. Thanks!
