### ISSUE TITLE
Need video to play inline on device.

### ISSUE THREAD

**Issue by pbvcity** [stakes/Frameless#15]
Thank you for your work. It really helps in my work.
But I found even though I set "webkit-playsinline" to video, it still automatically play fullscreen.
According to this:
https://developer.apple.com/library/ios/documentation/uikit/reference/UIWebView_Class/index.html#//apple_ref/occ/instp/UIWebView/allowsInlineMediaPlayback
The value of allowsInlineMediaPlayback should be yes.

I really need this to test my work. Could you please change it in the future version?

**Comment by hhumphrey84** [comment]
Hi – This issue seems to have reoccurred, I've tested using the master branch and spot that allowsInlineMediaPlayback is set to true but still the video loads full screen. Any idea?
