### ISSUE TITLE
Add support for basic http authentication

### ISSUE THREAD

**Issue by andyhawkes** [stakes/Frameless#24]
It would be very useful to be able to access development sites which use basic http authentication - this does not currently appear to be supported.

**Comment by ppo** [comment]
+1

**Comment by crstauf** [comment]
+1

**Comment by infinityplusone** [comment]
+1

**Comment by infinityplusone** [comment]
Any chance this is going to happen (soon)?

**Comment by stakes** [comment]
Your wishes = my command

https://github.com/stakes/Frameless/commit/eab66ae0d044c7d109830a9e61923d30633fc34c

**Comment by stakes** [comment]
Support for basic http auth will be in the next app store build and it's also now in the master branch if you want to grab that and build. Enjoy :tada:

**Comment by infinityplusone** [comment]
Well, that was impressive. (Haven't tested it out yet, but the 2-hour turnaround was nice...)

**Comment by stakes** [comment]
I live to serve. (Actually I start a new job Friday so everyone bumping this issue was a timely reminder that it's now or never to get this in there...)

**Comment by ppo** [comment]
Thanks :-)
