### ISSUE TITLE
Offline cache size?

### ISSUE THREAD

**Issue by ichabodcole** [stakes/Frameless#32]
Does Frameless support offline file caching via a cache.manifest file? Having issues getting it to work?

If so are there any specs on the total offline cache size, and limits on caching individual file size for frameless?
The issue I'm having is that I'd like to be able to display an app offline that includes some videos which are in the 10s of megabytes, and right now I seem to be hitting some limit that is breaking the offline caching (in ios safari).
Any guidance appreciated.

**Comment by stakes** [comment]
I'll look into this at some point, sorry for the late reply!

**Comment by stakes** [comment]
Imma close this out because Framer Studio doesn't support offline cache anymore and that's the primary use case for Frameless. (https://www.facebook.com/groups/framerjs/permalink/623659084427833)
