### ISSUE TITLE
Tapping "options" button crashes App on iPad with iOS 8.3 (latest)

### ISSUE THREAD

**Issue by scalabl3** [stakes/Frameless#43]
Can't tap options button, always crashes immediately (so cannot change any options, or do anything that is only available from the options screen!)

**Comment by scalabl3** [comment]
Sorry, if it helps, it is an iPad Mini 2 Retina with iOS 8.3 (latest), and behaves the same in landscape and portrait modes.

**Comment by stakes** [comment]
Are you using the app store version or building from the repo? Does your build include this commit?

https://github.com/stakes/Frameless/commit/09990dec7ed654737081f17c1b2f868f888238d5

Just wanna be sure what to look at, thx!

**Comment by Camissa** [comment]
This is happening for me too.  On an iPad 2, iOS 8.3 using the app store version.

**Comment by stakes** [comment]
Gonna be fixed in the next update (provided that https://github.com/stakes/Frameless/commit/09990dec7ed654737081f17c1b2f868f888238d5 in fact does fix the issue) - thanks!
