### ISSUE TITLE
Crashes when launched via URL scheme

### ISSUE THREAD

**Issue by timonus** [stakes/Frameless#55]
I'm attempting to integrate Frameless into [Opener](http://opener.link), and when launching via the URL scheme the app crashes after loading for a little while. This is pretty consistent on actual hardware, you can see it with [frameless://www.opener.link](frameless://www.opener.link) for example, but doesn't seem to happen in the sim.

**Comment by lubieapki** [comment]
the same, any solutions?

**Comment by timonus** [comment]
Not that I know of.

**Comment by jordandobson** [comment]
It's missing the trailing slash... I think he fixed this.

**Comment by jordandobson** [comment]
Fixed it in the module I meant.

**Comment by lubieapki** [comment]
![zrzut ekranu 2016-01-26 o 09 57 12](https://cloud.githubusercontent.com/assets/6787484/12576374/8468a022-c413-11e5-868c-20280c0c7ad1.png)

**Comment by timonus** [comment]
Ah, sweet! Just added support for Frameless to Opener in https://github.com/timonus/OpenerManifest/commit/f9418c0df9685add59dc8f135f35d2e2744cb52f.
